name: Build APK Clean Reset

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout kode aplikasi
        uses: actions/checkout@v4

      - name: Setup Mesin Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Komponen Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git openjdk-17-jdk unzip zip autoconf automake libtool pkg-config libffi-dev
          python -m pip install --upgrade pip setuptools wheel
          pip install buildozer cython==0.29.33 virtualenv

      - name: Mulai Perakitan APK
        run: |
          yes | buildozer -v android debug

      - name: Upload Hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: GoLockers-APK
          path: bin/*.apk
